-- Table: store.categories

-- DROP TABLE store.categories;

CREATE TABLE store.categories
(
    id integer NOT NULL DEFAULT nextval('store.categories_id_seq'::regclass),
    name text COLLATE pg_catalog."default",
    display_name text COLLATE pg_catalog."default",
    CONSTRAINT categories_pkey PRIMARY KEY (id)
)
WITH (
    OIDS = FALSE
)
TABLESPACE pg_default;

ALTER TABLE store.categories
    OWNER to admin_store;
COMMENT ON TABLE store.categories
    IS 'Categories table';
